### ISSUE TITLE
Windows Server 2003 VM support

### ISSUE THREAD

**Issue by Zero3K** [csm10495/nvmewin#1]
It would be nice if it you could get it to work in a x86/x64 Windows Server 2003 VM. I tried the version available at https://sourceforge.net/projects/nvme-for-windows-2003-server/ (which didn't work in either architecture). It gave me a "Code 10" error in its Properties that is available via Device Manager and froze the OS when trying to boot with a disk image associated to the NVMe controller that I had added to the VM's settings (both VMWare Workstation Player 15 and VirtualBox resulted in the same thing happening).

**Comment by Zero3K** [comment]
I tried using WDK 7600.16385.1 to build it under the Windows Server 2003 x86 Checked Build Environment using the attached .cmd and it didn't work (it told me that it was missing some files):

[make_chk.zip](https://github.com/csm10495/nvmewin/files/3587059/make_chk.zip)

**Comment by csm10495** [comment]
Server 2003 is really old and past EOL at this point. I'm not even sure
this would work with Server 2008. You could try ensuring you have the
latest service pack as I believe it added support for storport which may
help us not fall into scsiport support.

I made very few changes to base functionality from the original OFA driver
besides some new Ioctls. This is likely outside my realm.

Do you have a dbgview log of the code 10 on enable? Maybe it's something
obvious from there, otherwise not much I can do to help out

**Comment by Zero3K** [comment]
I wasn't able to get any debug output with the build I was using. Which is why I wanted to use yours since you added some debug output. The reason why I want support for Windows Server 2003 is because ReactOS uses it as a base.

**Comment by Zero3K** [comment]
"Windows cannot load the device driver for this hardware. The driver may be corrupted or missing. (Code 39)" Is what I get when I try to install the driver in a Windows Server 2003 x86 VM.

**Comment by csm10495** [comment]
Odd. No idea, unfortunately.

**Comment by Zero3K** [comment]
I think its because its a Windows 7 driver trying to load in Windows Server 2003.

**Comment by Zero3K** [comment]
And when I tried adding the two files (generated using Visual Studio 2017) in the attached archive to the source directory then running the .cmd I attached earlier, I get a bunch of errors:

[nvmeMofData.zip](https://github.com/csm10495/nvmewin/files/3587091/nvmeMofData.zip)

EDIT: Maybe you could take a look at the source code of the driver that I linked to in the Issue's description and see if there's anything that points to it not working or use it as a reference to get yours compiling for Windows Server 2003.

**Comment by Zero3K** [comment]
(sdk/lib/rtl/image.c:428) Unknown/unsupported fixup type 11.
(sdk/lib/rtl/image.c:430) Address 00746008, Current 0, Count 2181, *TypeOffset b924
(sdk/lib/rtl/image.c:505) Error during call to LdrProcessRelocationBlockLongLong()!
(../boot/freeldr/freeldr/ntldr/winldr.c:335) err: Can't load boot driver 'System32\drivers\nvme.sys'!

That is what one guy who tried the driver had happen for him in ReactOS.

**Comment by Zero3K** [comment]
You could try joining https://chat.reactos.org/reactos/channels/development and asking for help on getting it to work in Windows Server 2003/ReactOS.

**Comment by csm10495** [comment]
I'm not likely to work on this request. You're free to contact them if you want to work on it and pull request a solution

**Comment by Zero3K** [comment]
I did but they told me they won't consider working on it, etc. until it works in Windows Server 2003. By the way, I'm not a developer.

**Comment by Zero3K** [comment]
I tried asking other developers but they are either too busy or not interested.

EDIT: Getting it to where it can be compiled for Windows Server 2003 x86/x64 shouldn't be too hard to do.

**Comment by Zero3K** [comment]
Any more thoughts?

**Comment by csm10495** [comment]
You are free to do it and pull request if you would like.

**Comment by Zero3K** [comment]
I might as well close this issue then since I am not a developer and no one wants to help.

**Comment by Zero3K** [comment]
I hope I am wrong and someone does help soon.

**Comment by Zero3K** [comment]
I'm going to close it. Sorry for wasting your time.
