### ISSUE TITLE
Suggestion regarding the Releases

### ISSUE THREAD

**Issue by Zero3K** [csm10495/nvmewin#2]
They should be a ZIP archive containing compiled x86 and x64 drivers along with the pass-through program.

**Comment by csm10495** [comment]
I don't plan on releasing the driver as a compiled build because it isn't
signed and is not currently fit for use outside of targeted bench testing.

**Comment by Zero3K** [comment]
Later on then?

**Comment by csm10495** [comment]
Highly doubt it since among other reasons it won't be production signed
